<a href="https://colab.research.google.com/github/alifia07nisa/coba/blob/main/Pertemuan10_Alifia_Choirunnisa_250401020010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Alifia Choirunnisa

NIM : 250401020010

Kelas : IF403

In [15]:
#Muat dan Eksplorasi Data

import pandas as pd

url = "https://drive.google.com/uc?id=1wmVjvkNW0fRk3htK0elhaC1c1I9DRKDT"
df = pd.read_csv(url)

print(df.shape)
print(df["Churn"].value_counts(normalize=True))

df.head()

(7043, 21)
Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
#Preprocessing
from sklearn.model_selection import train_test_split
#TODO: encoding fitur kategorikal (mis. pd.get_dummies)
df = pd.get_dummies(df, drop_first=True)

#TODO: pisahkan X (fitur) dan y (target = Churn)
X = df.drop('Churn_Yes', axis=1)
y = df['Churn_Yes']

#Membagi data menjadi data latih dan data uji
X_tr, X_te, y_tr, y_te = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Ukuran data latih:", X_tr.shape)
print("Ukuran data uji:", X_te.shape)

Ukuran data latih: (5634, 13601)
Ukuran data uji: (1409, 13601)

In [17]:
from sklearn.ensemble import RandomForestClassifier

#Membangun model Random Forest
rf = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42
)

#Melatih model menggunakan data latih
rf.fit(X_tr, y_tr)

RandomForestClassifier(class_weight='balanced', n_estimators=300,
                       random_state=42)

In [18]:
from sklearn.metrics import classification_report, roc_auc_score

#Menghitung prediksi
y_pred = rf.predict(X_te)

#Menghitung probabilitas kelas 1 (Churn = Yes)
y_prob = rf.predict_proba(X_te)[:, 1]

#Menampilkan classification report
print(classification_report(y_te, y_pred))

#Menghitung dan menampilkan ROC-AUC
roc_auc = roc_auc_score(y_te, y_prob)
print("ROC-AUC:", roc_auc)

              precision    recall  f1-score   support

       False       0.84      0.90      0.87      1035
        True       0.65      0.52      0.58       374

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

ROC-AUC: 0.8337260068717869

In [19]:
#Menghitung probabilitas churn (kelas 1)
churn_prob = rf.predict_proba(X_te)[:, 1]

#Menampilkan 10 probabilitas pertama
#print(churn_prob[:10])

import pandas as pd

hasil = pd.DataFrame({
    "Probabilitas_Churn": churn_prob,
    "Persentase_Churn (%)": (churn_prob * 100).round(2)
})

hasil.head(10)

   Probabilitas_Churn  Persentase_Churn (%)
0            0.003333                  0.33
1            0.636667                 63.67
2            0.073333                  7.33
3            0.376667                 37.67
4            0.016667                  1.67
5            0.566667                 56.67
6            0.463333                 46.33
7            0.030000                  3.00
8            0.003333                  0.33
9            0.530000                 53.00

Berdasarkan hasil prediksi probabilitas, Random Forest mampu memberikan estimasi kemungkinan setiap pelanggan akan melakukan churn. Nilai probabilitas yang mendekati 1 atau 100% menunjukkan pelanggan memiliki kemungkinan churn yang lebih tinggi, sedangkan nilai yang mendekati 0 menunjukkan pelanggan memiliki kemungkinan lebih tinggi untuk tetap menggunakan layanan. Hasil prediksi ini dapat digunakan oleh perusahaan untuk mengidentifikasi pelanggan mana saja yang terdapat kemungkinan untuk melakukan churn dan merencanakan strategi agar pelanggan tetap menggunakan layanan.